_id: O9iRMVgTpQn2qH1H
_key: "!items!O9iRMVgTpQn2qH1H"
effects: []
flags:
  pf1: {}
  pf1spheres:
    casterProgression: mid
folder: null
img: icons/svg/item-bag.svg
name: Prodigy
sort: 0
system:
  alignment: ""
  armorProf:
    custom: []
    value: []
  bab: med
  changeFlags:
    heavyArmorFullSpeed: false
    loseDexToAC: false
    mediumArmorFullSpeed: false
    noHeavyEncumbrance: false
    noMediumEncumbrance: false
  changes: []
  classSkills:
    acr: true
    apr: false
    art: true
    blf: true
    clm: true
    crf: true
    dev: false
    dip: true
    dis: false
    esc: false
    fly: false
    han: false
    hea: false
    int: true
    kar: true
    kdu: true
    ken: true
    kge: true
    khi: true
    klo: true
    kna: true
    kno: true
    kpl: true
    kre: true
    lin: false
    lor: false
    per: true
    prf: true
    pro: true
    rid: false
    sen: true
    slt: false
    spl: true
    ste: false
    sur: false
    swm: false
    umd: true
  customHD: ""
  description:
    unidentified: ""
    value: >
      “I can do that.”

      <p>Brilliant warriors capable of combining martial and magic techniques
      into a seamless flow, bewildering allies and confounding foes with their
      flashes of inspiration that grant them unforeseen capability.</p>

      <p><strong>Role:</strong> Prodigies are a diverse group, capable of
      filling many roles.</p>

      <p><strong>Alignment:</strong> Any.</p>

      <p><strong>Hit Die:</strong> d8</p>

      <p><strong>Starting Wealth:</strong> 3d6 x 10 gp (average 105 gp). In
      addition, each character begins play with an outfit worth 10 gp or
      less.</p>

      <p><strong>Starting Age:</strong> Intuitive.</p>

      <p><strong>Class Skills:</strong> The prodigy&#8217;s class skills are
      Acrobatics (Dex), Bluff (Cha), Climb (Str), Craft (Int), Diplomacy (Cha),
      Intimidate (Cha), Knowledge (all) (Int), Perception (Wis), Perform (Cha),
      Profession (Wis), Sense Motive (Wis), Spellcraft (Int), Use Magic Device
      (Cha), and three other class skills of the prodigy&#8217;s choice, chosen
      at character creation.</p>

      <p><strong>Skill Ranks Per Level:</strong> 4 + Int modifier.</p>
  fc:
    alt:
      notes: ""
      value: 0
    hp:
      value: 0
    skill:
      value: 0
  flags:
    boolean: {}
    dictionary: {}
  hd: 8
  hp: 8
  languages:
    custom: []
    value: []
  level: 1
  links:
    children: []
    classAssociations:
      - level: 1
        name: Proficiencies (Prodigy)
        uuid: Compendium.pf1spheres.class-features.in7ZowePvey2zpMk
      - level: 1
        name: Casting (Prodigy)
        uuid: Compendium.pf1spheres.class-features.FZkmw7hEECEh4KOx
      - level: 1
        name: Spell Pool (Prodigy)
        uuid: Compendium.pf1spheres.class-features.qsFtbOc0wpg2YvDp
      - level: 1
        name: Blended Training (Prodigy)
        uuid: Compendium.pf1spheres.class-features.9eZIQLjyGgGW6tF0
      - level: 1
        name: Sequence
        uuid: Compendium.pf1spheres.class-features.iGvTsm4MQ5GDPD3p
      - level: 1
        name: Integrated Techniques
        uuid: Compendium.pf1spheres.class-features.eAsBbuEwHaRRn7QO
      - level: 1
        name: Inspired Sequence
        uuid: Compendium.pf1spheres.class-features.z1F5olJGDpfgavDC
      - level: 2
        name: Adaptation (Prodigy)
        uuid: Compendium.pf1spheres.class-features.OIlaLry8OBdiYZox
      - level: 2
        name: Imbue Sequence
        uuid: Compendium.pf1spheres.class-features.30w5iBgJ2qGKHtgy
      - level: 3
        name: Steady Skill
        uuid: Compendium.pf1spheres.class-features.Ou4Xal4fN2DeH0Oi
      - level: 4
        name: Unbroken Sequence
        uuid: Compendium.pf1spheres.class-features.fuHRYS4nY44yHmoU
      - level: 5
        name: Improved Adaptation
        uuid: Compendium.pf1spheres.class-features.NLFLOOoGXBjZSDHB
      - level: 7
        name: Reflect Spell
        uuid: Compendium.pf1spheres.class-features.ep20uAh0u3rGjNBR
      - level: 8
        name: Greater Adaptation
        uuid: Compendium.pf1spheres.class-features.fOwj5Q5XEcVXrSpI
      - level: 10
        name: Share Adaptation
        uuid: Compendium.pf1spheres.class-features.8n6oLXHIUJn1ZnJA
      - level: 11
        name: Variable Skill
        uuid: Compendium.pf1spheres.class-features.ofAWxpBzYayX8A8n
      - level: 13
        name: Master Adaptation
        uuid: Compendium.pf1spheres.class-features.ozmrdUGSZLKakwNV
      - level: 14
        name: Flawless Sequence
        uuid: Compendium.pf1spheres.class-features.yFiGJrkpr9mkSJfw
      - level: 16
        name: Greater Reflect Spell
        uuid: Compendium.pf1spheres.class-features.FIH4XMWKdrq2eeKx
      - level: 17
        name: Grandmaster Adaptation
        uuid: Compendium.pf1spheres.class-features.TwpHpdJhkzIyVo9i
      - level: 19
        name: Skill Juggler
        uuid: Compendium.pf1spheres.class-features.PVhNYKN6x13VCP76
      - level: 20
        name: Perfected Prodigy
        uuid: Compendium.pf1spheres.class-features.e9X1LzMrBsfWBdNB
  savingThrows:
    fort:
      value: low
    ref:
      value: high
    will:
      value: high
  scriptCalls: []
  skillsPerLevel: 4
  subType: base
  tag: ""
  tags: []
  wealth: ""
  weaponProf:
    custom: []
    value: []
type: class
