import { FakeActorDataSource } from "./fakes";

// @ts-expect-error Export is what it is
export const testActor: FakeActorDataSource = {
  name: "Sphere Tester",
  type: "character",
  img: "icons/svg/mystery-man.svg",
  data: {
    abilities: {
      str: {
        value: 10,
        carryBonus: 0,
        carryMultiplier: 1,
        damage: 0,
        drain: 0,
        userPenalty: 0,
        total: 10,
        mod: 0,
        checkMod: 0,
        penalty: 0,
        base: 10,
        baseMod: 0,
      },
      dex: {
        value: 10,
        damage: 0,
        drain: 0,
        userPenalty: 0,
        total: 10,
        mod: 0,
        checkMod: 0,
        penalty: 0,
        base: 10,
        baseMod: 0,
      },
      con: {
        value: 10,
        damage: 0,
        drain: 0,
        userPenalty: 0,
        total: 10,
        mod: 0,
        checkMod: 0,
        penalty: 0,
        base: 10,
        baseMod: 0,
      },
      int: {
        value: 10,
        damage: 0,
        drain: 0,
        userPenalty: 0,
        total: 10,
        mod: 0,
        checkMod: 0,
        penalty: 0,
        base: 10,
        baseMod: 0,
      },
      wis: {
        value: 10,
        damage: 0,
        drain: 0,
        userPenalty: 0,
        total: 10,
        mod: 0,
        checkMod: 0,
        penalty: 0,
        base: 10,
        baseMod: 0,
      },
      cha: {
        value: 10,
        damage: 0,
        drain: 0,
        userPenalty: 0,
        total: 10,
        mod: 0,
        checkMod: 0,
        penalty: 0,
        base: 10,
        baseMod: 0,
      },
    },
    resources: {},
    attributes: {
      hpAbility: "con",
      cmbAbility: "str",
      naturalAC: 0,
      ac: {
        normal: {
          ability: "dex",
          value: 0,
          total: 10,
        },
        touch: {
          ability: "dex",
          value: 0,
          total: 10,
        },
        flatFooted: {
          value: 0,
          total: 10,
        },
      },
      cmd: {
        dexAbility: "dex",
        value: 0,
        total: 10,
        flatFootedTotal: 10,
      },
      sr: {
        formula: "",
        total: 0,
      },
      saveNotes: "",
      acNotes: "",
      cmdNotes: "",
      srNotes: "",
      attack: {
        meleeAbility: "str",
        rangedAbility: "dex",
        general: 0,
        shared: 0,
        melee: 0,
        ranged: 0,
      },
      energyDrain: 0,
      quadruped: false,
      savingThrows: {
        fort: {
          base: 0,
          ability: "con",
          total: 0,
        },
        ref: {
          base: 0,
          ability: "dex",
          total: 0,
        },
        will: {
          base: 0,
          ability: "wis",
          total: 0,
        },
      },
      hp: {
        value: 33,
        base: 0,
        temp: 0,
        nonlethal: 0,
        max: 0,
      },
      wounds: {
        min: 0,
        base: 0,
        value: 0,
        max: 0,
      },
      vigor: {
        min: 0,
        value: 33,
        temp: 0,
        base: 0,
        max: 0,
      },
      init: {
        value: 0,
        ability: "dex",
        bonus: 0,
        total: 0,
      },
      speed: {
        land: {
          base: 30,
          total: 30,
        },
        climb: {
          base: 0,
          total: null,
        },
        swim: {
          base: 0,
          total: null,
        },
        burrow: {
          base: 0,
          total: null,
        },
        fly: {
          base: 0,
          maneuverability: "average",
          total: null,
        },
      },
      conditions: {
        bleed: false,
        blind: false,
        confused: false,
        dazed: false,
        dazzled: false,
        deaf: false,
        entangled: false,
        fatigued: false,
        frightened: false,
        exhausted: false,
        grappled: false,
        helpless: false,
        incorporeal: false,
        invisible: false,
        nauseated: false,
        panicked: false,
        paralyzed: false,
        pinned: false,
        prone: false,
        shaken: false,
        sickened: false,
        staggered: false,
        stunned: false,
        battered: true,
      },
      spells: {
        usedSpellbooks: [],
        spellbooks: {
          primary: {
            altName: "",
            castPerDayAllOffsetFormula: "",
            preparedAllOffsetFormula: "",
            name: "Primary",
            casterType: "high",
            class: "",
            cl: {
              formula: "",
              base: 0,
              value: 0,
              total: 0,
            },
            concentrationFormula: "",
            concentrationNotes: "",
            clNotes: "",
            ability: "int",
            autoSpellLevelCalculation: true,
            autoSpellLevels: true,
            arcaneSpellFailure: true,
            hasCantrips: true,
            spellPreparationMode: "spontaneous",
            baseDCFormula: "10 + @sl + @ablMod",
            spontaneous: false,
            spellPoints: {
              useSystem: false,
              value: 0,
              maxFormula: "",
              restoreFormula: "",
              max: 0,
            },
            spells: {
              spell0: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell1: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell2: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell3: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell4: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell5: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell6: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell7: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell8: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell9: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
            },
            spellSlotAbilityBonusFormula: "",
            domainSlotValue: 1,
            concentration: 0,
          },
          secondary: {
            altName: "",
            castPerDayAllOffsetFormula: "",
            preparedAllOffsetFormula: "",
            name: "Secondary",
            casterType: "high",
            class: "",
            cl: {
              formula: "",
              base: 0,
              value: 0,
              total: 0,
            },
            concentrationFormula: "",
            concentrationNotes: "",
            clNotes: "",
            ability: "int",
            autoSpellLevelCalculation: true,
            autoSpellLevels: true,
            arcaneSpellFailure: true,
            hasCantrips: true,
            spellPreparationMode: "spontaneous",
            baseDCFormula: "10 + @sl + @ablMod",
            spontaneous: false,
            spellPoints: {
              useSystem: false,
              value: 0,
              maxFormula: "",
              restoreFormula: "",
              max: 0,
            },
            spells: {
              spell0: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell1: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell2: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell3: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell4: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell5: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell6: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell7: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell8: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell9: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
            },
            spellSlotAbilityBonusFormula: "",
            domainSlotValue: 1,
            concentration: 0,
          },
          tertiary: {
            altName: "",
            castPerDayAllOffsetFormula: "",
            preparedAllOffsetFormula: "",
            name: "Tertiary",
            casterType: "high",
            class: "",
            cl: {
              formula: "",
              base: 0,
              value: 0,
              total: 0,
            },
            concentrationFormula: "",
            concentrationNotes: "",
            clNotes: "",
            ability: "int",
            autoSpellLevelCalculation: true,
            autoSpellLevels: true,
            arcaneSpellFailure: true,
            hasCantrips: true,
            spellPreparationMode: "spontaneous",
            baseDCFormula: "10 + @sl + @ablMod",
            spontaneous: false,
            spellPoints: {
              useSystem: false,
              value: 0,
              maxFormula: "",
              restoreFormula: "",
              max: 0,
            },
            spells: {
              spell0: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell1: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell2: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell3: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell4: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell5: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell6: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell7: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell8: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell9: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
            },
            spellSlotAbilityBonusFormula: "",
            domainSlotValue: 1,
            concentration: 0,
          },
          spelllike: {
            altName: "",
            castPerDayAllOffsetFormula: "",
            preparedAllOffsetFormula: "",
            name: "Spell-likes",
            casterType: "high",
            class: "_hd",
            cl: {
              formula: "",
              base: 0,
              value: 0,
              total: 0,
            },
            concentrationFormula: "",
            concentrationNotes: "",
            clNotes: "",
            ability: "cha",
            autoSpellLevelCalculation: true,
            autoSpellLevels: true,
            arcaneSpellFailure: true,
            hasCantrips: true,
            spellPreparationMode: "spontaneous",
            baseDCFormula: "10 + @sl + @ablMod",
            spontaneous: false,
            spellPoints: {
              useSystem: false,
              value: 0,
              maxFormula: "",
              restoreFormula: "",
              max: 0,
            },
            spells: {
              spell0: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell1: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell2: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell3: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
              },
              spell4: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell5: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell6: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell7: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell8: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
              spell9: {
                castPerDayOffsetFormula: "",
                preparedOffsetFormula: "",
                base: "",
              },
            },
            spellSlotAbilityBonusFormula: "",
            domainSlotValue: 1,
            concentration: 0,
          },
        },
      },
      encumbrance: {
        level: 0,
        levels: {
          light: 33,
          medium: 66,
          heavy: 100,
          carry: 200,
          drag: 500,
        },
        carriedWeight: 0,
      },
      hd: {
        total: 1,
        max: {
          _deprecated: true,
          value: 0,
        },
      },
      bab: {
        value: 0,
        total: 0,
      },
      cmb: {
        value: 0,
        total: 0,
      },
      damage: {
        general: 0,
        weapon: 0,
        spell: 0,
      },
      maxDexBonus: null,
      mDex: {
        armorBonus: 0,
        shieldBonus: 0,
      },
      acp: {
        gear: 0,
        encumbrance: 0,
        total: 0,
        armorBonus: 0,
        shieldBonus: 0,
        attackPenalty: 0,
      },
      woundThresholds: {
        penalty: 0,
        mod: 0,
        level: 0,
        override: -1,
      },
      prof: 2,
      spellcasting: {
        _deprecated: true,
      },
      spelldc: {
        _deprecated: true,
      },
      creatureType: "humanoid",
    },
    details: {
      level: {
        value: 0,
        min: 0,
        max: 40,
      },
      bonusFeatFormula: "",
      alignment: "tn",
      biography: {
        value: "",
        public: "",
      },
      notes: {
        value: "",
        public: "",
      },
      bonusSkillRankFormula: "",
      tooltip: {
        name: "",
        hideHeld: false,
        hideArmor: false,
        hideBuffs: false,
        hideConditions: false,
        hideClothing: false,
        hideName: false,
      },
      xp: {
        value: 0,
        min: 0,
        max: 300,
      },
      height: "",
      weight: "",
      gender: "",
      deity: "",
      age: "",
      mythicTier: 0,
      cr: {
        base: 1,
        total: 1,
      },
    },
    skills: {
      acr: {
        ability: "dex",
        rt: false,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      apr: {
        ability: "int",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      art: {
        ability: "int",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      blf: {
        ability: "cha",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      clm: {
        ability: "str",
        rt: false,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      crf: {
        ability: "int",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      dip: {
        ability: "cha",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      dev: {
        ability: "dex",
        rt: true,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      dis: {
        ability: "cha",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      esc: {
        ability: "dex",
        rt: false,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      fly: {
        ability: "dex",
        rt: false,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      han: {
        ability: "cha",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      hea: {
        ability: "wis",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      int: {
        ability: "cha",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      kar: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      kdu: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      ken: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      kge: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      khi: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      klo: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      kna: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      kno: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      kpl: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      kre: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      lin: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      lor: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      per: {
        ability: "wis",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      prf: {
        ability: "cha",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      pro: {
        ability: "wis",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      rid: {
        ability: "dex",
        rt: false,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      sen: {
        ability: "wis",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      slt: {
        ability: "dex",
        rt: true,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: true,
      },
      spl: {
        ability: "int",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      ste: {
        ability: "dex",
        rt: false,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      sur: {
        ability: "wis",
        rt: false,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      swm: {
        ability: "str",
        rt: false,
        acp: true,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
      umd: {
        ability: "cha",
        rt: true,
        acp: false,
        rank: 0,
        value: 0,
        mod: 0,
        background: false,
      },
    },
    customSkills: {},
    traits: {
      size: "med",
      senses: "",
      dr: "",
      eres: "",
      cres: "",
      regen: "",
      fastHealing: "",
      languages: {
        value: [],
        custom: "",
      },
      di: {
        value: [],
        custom: "",
      },
      dv: {
        value: [],
        custom: "",
      },
      ci: {
        value: [],
        custom: "",
      },
      stature: "tall",
      weaponProf: {
        value: [],
        custom: "",
      },
      armorProf: {
        value: [],
        custom: "",
      },
      perception: {
        _deprecated: true,
      },
    },
    currency: {
      pp: 0,
      gp: 0,
      sp: 0,
      cp: 0,
    },
    altCurrency: {
      pp: 0,
      gp: 0,
      sp: 0,
      cp: 0,
    },
  },
  token: {
    name: "Sphere Tester",
    img: "icons/svg/mystery-man.svg",
    displayName: 0,
    actorLink: true,
    width: 1,
    height: 1,
    scale: 1,
    mirrorX: false,
    mirrorY: false,
    lockRotation: false,
    rotation: 0,
    alpha: 1,
    vision: false,
    dimSight: 0,
    brightSight: 0,
    dimLight: 0,
    brightLight: 0,
    sightAngle: 0,
    lightAngle: 0,
    lightAlpha: 0.25,
    lightAnimation: {
      speed: 5,
      intensity: 5,
    },
    disposition: -1,
    displayBars: 0,
    bar1: {
      attribute: "attributes.hp",
    },
    bar2: {
      attribute: null,
    },
    flags: {
      pf1: {
        lowLightVision: false,
      },
    },
    randomImg: false,
  },
  items: [
    {
      _id: "fYmqgofwjXKl8Tjg",
      name: "Low-Caster",
      type: "class",
      img: "icons/svg/item-bag.svg",
      data: {
        description: {
          value: "",
          chat: "",
          unidentified: "",
        },
        tags: [],
        changes: [],
        changeFlags: {
          loseDexToAC: false,
          noEncumbrance: false,
          mediumArmorFullSpeed: false,
          heavyArmorFullSpeed: false,
        },
        links: {
          children: [],
          classAssociations: [],
        },
        tag: "lowcaster",
        useCustomTag: false,
        armorProf: {
          value: [],
          custom: "",
        },
        weaponProf: {
          value: [],
          custom: "",
        },
        flags: {
          boolean: [],
          dictionary: [],
        },
        scriptCalls: [],
        classType: "base",
        level: 3,
        hd: 8,
        hp: 8,
        bab: "low",
        skillsPerLevel: 0,
        savingThrows: {
          fort: {
            value: "low",
          },
          ref: {
            value: "low",
          },
          will: {
            value: "low",
          },
        },
        fc: {
          hp: {
            value: 0,
          },
          skill: {
            value: 0,
          },
          alt: {
            value: 0,
            notes: "",
          },
        },
        classSkills: {
          acr: false,
          apr: false,
          art: false,
          blf: false,
          clm: false,
          crf: false,
          dip: false,
          dev: false,
          dis: false,
          esc: false,
          fly: false,
          han: false,
          hea: false,
          int: false,
          kar: false,
          kdu: false,
          ken: false,
          kge: false,
          khi: false,
          klo: false,
          kna: false,
          kno: false,
          kpl: false,
          kre: false,
          lin: false,
          lor: false,
          per: false,
          prf: false,
          pro: false,
          rid: false,
          sen: false,
          slt: false,
          spl: false,
          ste: false,
          sur: false,
          swm: false,
          umd: false,
        },
        levels: {
          value: 0,
          _deprecated: true,
        },
        conditionals: [],
        identifiedName: "Low-Caster",
        range: {
          maxIncrements: 1,
        },
      },
      effects: [],
      folder: null,
      sort: 0,
      permission: {
        default: 0,
        exBYpki8XOQ8AkUV: 3,
      },
      flags: {
        pf1spheres: {
          casterProgression: "low",
        },
      },
    },
    {
      _id: "3TWJBD4iVkYr9rD2",
      name: "Mid-Caster",
      type: "class",
      img: "icons/svg/item-bag.svg",
      data: {
        description: {
          value: "",
          chat: "",
          unidentified: "",
        },
        tags: [],
        changes: [],
        changeFlags: {
          loseDexToAC: false,
          noEncumbrance: false,
          mediumArmorFullSpeed: false,
          heavyArmorFullSpeed: false,
        },
        links: {
          children: [],
          classAssociations: [],
        },
        tag: "midcaster",
        useCustomTag: false,
        armorProf: {
          value: [],
          custom: "",
        },
        weaponProf: {
          value: [],
          custom: "",
        },
        flags: {
          boolean: [],
          dictionary: [],
        },
        scriptCalls: [],
        classType: "base",
        level: 2,
        hd: 8,
        hp: 8,
        bab: "low",
        skillsPerLevel: 0,
        savingThrows: {
          fort: {
            value: "low",
          },
          ref: {
            value: "low",
          },
          will: {
            value: "low",
          },
        },
        fc: {
          hp: {
            value: 0,
          },
          skill: {
            value: 0,
          },
          alt: {
            value: 0,
            notes: "",
          },
        },
        classSkills: {
          acr: false,
          apr: false,
          art: false,
          blf: false,
          clm: false,
          crf: false,
          dip: false,
          dev: false,
          dis: false,
          esc: false,
          fly: false,
          han: false,
          hea: false,
          int: false,
          kar: false,
          kdu: false,
          ken: false,
          kge: false,
          khi: false,
          klo: false,
          kna: false,
          kno: false,
          kpl: false,
          kre: false,
          lin: false,
          lor: false,
          per: false,
          prf: false,
          pro: false,
          rid: false,
          sen: false,
          slt: false,
          spl: false,
          ste: false,
          sur: false,
          swm: false,
          umd: false,
        },
        levels: {
          value: 0,
          _deprecated: true,
        },
        conditionals: [],
        identifiedName: "Mid-Caster",
        range: {
          maxIncrements: 1,
        },
      },
      effects: [],
      folder: null,
      sort: 0,
      permission: {
        default: 0,
        exBYpki8XOQ8AkUV: 3,
      },
      flags: {
        pf1spheres: {
          casterProgression: "mid",
        },
      },
    },
    {
      _id: "DshQZgMA3V4DoD0c",
      name: "High-Caster",
      type: "class",
      img: "icons/svg/item-bag.svg",
      data: {
        description: {
          value: "",
          chat: "",
          unidentified: "",
        },
        tags: [],
        changes: [],
        changeFlags: {
          loseDexToAC: false,
          noEncumbrance: false,
          mediumArmorFullSpeed: false,
          heavyArmorFullSpeed: false,
        },
        links: {
          children: [],
          classAssociations: [],
        },
        tag: "highcaster",
        useCustomTag: false,
        armorProf: {
          value: [],
          custom: "",
        },
        weaponProf: {
          value: [],
          custom: "",
        },
        flags: {
          boolean: [],
          dictionary: [],
        },
        scriptCalls: [],
        classType: "base",
        level: 1,
        hd: 8,
        hp: 8,
        bab: "low",
        skillsPerLevel: 0,
        savingThrows: {
          fort: {
            value: "low",
          },
          ref: {
            value: "low",
          },
          will: {
            value: "low",
          },
        },
        fc: {
          hp: {
            value: 0,
          },
          skill: {
            value: 0,
          },
          alt: {
            value: 0,
            notes: "",
          },
        },
        classSkills: {
          acr: false,
          apr: false,
          art: false,
          blf: false,
          clm: false,
          crf: false,
          dip: false,
          dev: false,
          dis: false,
          esc: false,
          fly: false,
          han: false,
          hea: false,
          int: false,
          kar: false,
          kdu: false,
          ken: false,
          kge: false,
          khi: false,
          klo: false,
          kna: false,
          kno: false,
          kpl: false,
          kre: false,
          lin: false,
          lor: false,
          per: false,
          prf: false,
          pro: false,
          rid: false,
          sen: false,
          slt: false,
          spl: false,
          ste: false,
          sur: false,
          swm: false,
          umd: false,
        },
        levels: {
          value: 0,
          _deprecated: true,
        },
        conditionals: [],
        identifiedName: "High-Caster",
        range: {
          maxIncrements: 1,
        },
      },
      effects: [],
      folder: null,
      sort: 0,
      permission: {
        default: 0,
        exBYpki8XOQ8AkUV: 3,
      },
      flags: {
        pf1spheres: {
          casterProgression: "high",
        },
      },
    },
    {
      _id: "DZtczZEsEYginobW",
      name: "Combat Talent 1",
      type: "feat",
      img: "icons/svg/item-bag.svg",
      data: {
        description: {
          value: "",
          chat: "",
          unidentified: "",
        },
        tags: [],
        activation: {
          cost: 1,
          type: "",
        },
        unchainedAction: {
          activation: {
            cost: 1,
            type: "",
          },
        },
        duration: {
          value: null,
          units: "",
        },
        target: {
          value: "",
        },
        range: {
          value: null,
          units: "",
          maxIncrements: 1,
          minValue: null,
          minUnits: "",
        },
        uses: {
          value: 0,
          per: null,
          autoDeductCharges: true,
          autoDeductChargesCost: "1",
          max: 0,
        },
        measureTemplate: {
          type: "",
          size: "",
          overrideColor: false,
          customColor: "",
          overrideTexture: false,
          customTexture: "",
        },
        attackName: "",
        actionType: "",
        attackBonus: "",
        critConfirmBonus: "",
        damage: {
          parts: [],
          critParts: [],
          nonCritParts: [],
        },
        attackParts: [],
        formulaicAttacks: {
          count: {
            formula: "",
            value: null,
          },
          bonus: {
            formula: "",
          },
          label: null,
        },
        formula: "",
        ability: {
          attack: null,
          damage: null,
          damageMult: 1,
          critRange: 20,
          critMult: 2,
        },
        save: {
          dc: 0,
          type: "",
          description: "",
        },
        effectNotes: [],
        attackNotes: [],
        soundEffect: "",
        changes: [],
        changeFlags: {
          loseDexToAC: false,
          noEncumbrance: false,
          mediumArmorFullSpeed: false,
          heavyArmorFullSpeed: false,
        },
        contextNotes: [],
        links: {
          children: [],
          charges: [],
        },
        tag: "",
        useCustomTag: false,
        armorProf: {
          value: [],
          custom: "",
        },
        weaponProf: {
          value: [],
          custom: "",
        },
        flags: {
          boolean: [],
          dictionary: [],
        },
        scriptCalls: [],
        featType: "combatTalent",
        associations: {
          classes: [],
        },
        showInQuickbar: false,
        nonlethal: false,
        abilityType: "none",
        crOffset: "",
        disabled: false,
        conditionals: [],
        identifiedName: "Combat Talent 1",
      },
      effects: [],
      folder: null,
      sort: 0,
      permission: {
        default: 0,
        exBYpki8XOQ8AkUV: 3,
      },
      flags: {
        pf1spheres: {
          sphere: "athletics",
        },
      },
    },
    {
      _id: "UnMiv8vMg1OhwuCX",
      name: "Magic Talent 1",
      type: "feat",
      img: "icons/svg/item-bag.svg",
      data: {
        description: {
          value: "",
          chat: "",
          unidentified: "",
        },
        tags: [],
        activation: {
          cost: 1,
          type: "",
        },
        unchainedAction: {
          activation: {
            cost: 1,
            type: "",
          },
        },
        duration: {
          value: null,
          units: "",
        },
        target: {
          value: "",
        },
        range: {
          value: null,
          units: "",
          maxIncrements: 1,
          minValue: null,
          minUnits: "",
        },
        uses: {
          value: 0,
          per: null,
          autoDeductCharges: true,
          autoDeductChargesCost: "1",
          max: 0,
        },
        measureTemplate: {
          type: "",
          size: "",
          overrideColor: false,
          customColor: "",
          overrideTexture: false,
          customTexture: "",
        },
        attackName: "",
        actionType: "",
        attackBonus: "",
        critConfirmBonus: "",
        damage: {
          parts: [],
          critParts: [],
          nonCritParts: [],
        },
        attackParts: [],
        formulaicAttacks: {
          count: {
            formula: "",
            value: null,
          },
          bonus: {
            formula: "",
          },
          label: null,
        },
        formula: "",
        ability: {
          attack: null,
          damage: null,
          damageMult: 1,
          critRange: 20,
          critMult: 2,
        },
        save: {
          dc: 0,
          type: "",
          description: "",
        },
        effectNotes: [],
        attackNotes: [],
        soundEffect: "",
        changes: [],
        changeFlags: {
          loseDexToAC: false,
          noEncumbrance: false,
          mediumArmorFullSpeed: false,
          heavyArmorFullSpeed: false,
        },
        contextNotes: [],
        links: {
          children: [],
          charges: [],
        },
        tag: "",
        useCustomTag: false,
        armorProf: {
          value: [],
          custom: "",
        },
        weaponProf: {
          value: [],
          custom: "",
        },
        flags: {
          boolean: [],
          dictionary: [],
        },
        scriptCalls: [],
        featType: "magicTalent",
        associations: {
          classes: [],
        },
        showInQuickbar: false,
        nonlethal: false,
        abilityType: "none",
        crOffset: "",
        disabled: false,
        conditionals: [],
        identifiedName: "Magic Talent 1",
      },
      effects: [],
      folder: null,
      sort: 0,
      permission: {
        default: 0,
        exBYpki8XOQ8AkUV: 3,
      },
      flags: {
        pf1spheres: {
          sphere: "dark",
        },
      },
    },
    {
      _id: "OMU0bnITf2UGrZuB",
      name: "HD-CAP CL Trait",
      type: "feat",
      img: "icons/svg/item-bag.svg",
      data: {
        description: {
          value: "",
          chat: "",
          unidentified: "",
        },
        tags: [],
        activation: {
          cost: 1,
          type: "",
        },
        unchainedAction: {
          activation: {
            cost: 1,
            type: "",
          },
        },
        duration: {
          value: null,
          units: "",
        },
        target: {
          value: "",
        },
        range: {
          value: null,
          units: "",
          maxIncrements: 1,
          minValue: null,
          minUnits: "",
        },
        uses: {
          value: 0,
          per: null,
          autoDeductCharges: true,
          autoDeductChargesCost: "1",
          max: 0,
        },
        measureTemplate: {
          type: "",
          size: "",
          overrideColor: false,
          customColor: "",
          overrideTexture: false,
          customTexture: "",
        },
        attackName: "",
        actionType: "",
        attackBonus: "",
        critConfirmBonus: "",
        damage: {
          parts: [],
          critParts: [],
          nonCritParts: [],
        },
        attackParts: [],
        formulaicAttacks: {
          count: {
            formula: "",
            value: null,
          },
          bonus: {
            formula: "",
          },
          label: null,
        },
        formula: "",
        ability: {
          attack: null,
          damage: null,
          damageMult: 1,
          critRange: 20,
          critMult: 2,
        },
        save: {
          dc: 0,
          type: "",
          description: "",
        },
        effectNotes: [],
        attackNotes: [],
        soundEffect: "",
        changes: [
          {
            _id: "q57zo7vh",
            formula: "1",
            operator: "add",
            subTarget: "spherecl",
            modifier: "sphereCLCap",
            priority: 0,
            value: 1,
          },
        ],
        changeFlags: {
          loseDexToAC: false,
          noEncumbrance: false,
          mediumArmorFullSpeed: false,
          heavyArmorFullSpeed: false,
        },
        contextNotes: [],
        links: {
          children: [],
          charges: [],
        },
        tag: "",
        useCustomTag: false,
        armorProf: {
          value: [],
          custom: "",
        },
        weaponProf: {
          value: [],
          custom: "",
        },
        flags: {
          boolean: [],
          dictionary: [],
        },
        scriptCalls: [],
        featType: "trait",
        associations: {
          classes: [],
        },
        showInQuickbar: false,
        nonlethal: false,
        abilityType: "none",
        crOffset: "",
        disabled: false,
        conditionals: [],
        identifiedName: "HD-CAP CL Trait",
      },
      effects: [],
      folder: null,
      sort: 0,
      permission: {
        default: 0,
        exBYpki8XOQ8AkUV: 3,
      },
      flags: {},
    },
    {
      _id: "4UDhAEfix3PLfTBR",
      name: "Dark Feat",
      type: "feat",
      img: "icons/svg/item-bag.svg",
      data: {
        description: {
          value: "",
          chat: "",
          unidentified: "",
        },
        tags: [],
        activation: {
          cost: 1,
          type: "",
        },
        unchainedAction: {
          activation: {
            cost: 1,
            type: "",
          },
        },
        duration: {
          value: null,
          units: "",
        },
        target: {
          value: "",
        },
        range: {
          value: null,
          units: "",
          maxIncrements: 1,
          minValue: null,
          minUnits: "",
        },
        uses: {
          value: 0,
          per: null,
          autoDeductCharges: true,
          autoDeductChargesCost: "1",
          max: 0,
        },
        measureTemplate: {
          type: "",
          size: "",
          overrideColor: false,
          customColor: "",
          overrideTexture: false,
          customTexture: "",
        },
        attackName: "",
        actionType: "",
        attackBonus: "",
        critConfirmBonus: "",
        damage: {
          parts: [],
          critParts: [],
          nonCritParts: [],
        },
        attackParts: [],
        formulaicAttacks: {
          count: {
            formula: "",
            value: null,
          },
          bonus: {
            formula: "",
          },
          label: null,
        },
        formula: "",
        ability: {
          attack: null,
          damage: null,
          damageMult: 1,
          critRange: 20,
          critMult: 2,
        },
        save: {
          dc: 0,
          type: "",
          description: "",
        },
        effectNotes: [],
        attackNotes: [],
        soundEffect: "",
        changes: [
          {
            _id: "f9h709sf",
            formula: "2",
            operator: "add",
            subTarget: "sphereclDark",
            modifier: "untyped",
            priority: 0,
            value: 2,
          },
        ],
        changeFlags: {
          loseDexToAC: false,
          noEncumbrance: false,
          mediumArmorFullSpeed: false,
          heavyArmorFullSpeed: false,
        },
        contextNotes: [],
        links: {
          children: [],
          charges: [],
        },
        tag: "",
        useCustomTag: false,
        armorProf: {
          value: [],
          custom: "",
        },
        weaponProf: {
          value: [],
          custom: "",
        },
        flags: {
          boolean: [],
          dictionary: [],
        },
        scriptCalls: [],
        featType: "feat",
        associations: {
          classes: [],
        },
        showInQuickbar: false,
        nonlethal: false,
        abilityType: "none",
        crOffset: "",
        disabled: false,
        conditionals: [],
        identifiedName: "Dark Feat",
      },
      effects: [],
      folder: null,
      sort: 0,
      permission: {
        default: 0,
        exBYpki8XOQ8AkUV: 3,
      },
      flags: {},
    },
    {
      _id: "utpSvbGmzaym2AIX",
      name: "Sphere BAB Feat",
      type: "feat",
      img: "icons/svg/item-bag.svg",
      data: {
        description: {
          value: "",
          chat: "",
          unidentified: "",
        },
        tags: [],
        activation: {
          cost: 1,
          type: "",
        },
        unchainedAction: {
          activation: {
            cost: 1,
            type: "",
          },
        },
        duration: {
          value: null,
          units: "",
        },
        target: {
          value: "",
        },
        range: {
          value: null,
          units: "",
          maxIncrements: 1,
          minValue: null,
          minUnits: "",
        },
        uses: {
          value: 0,
          per: null,
          autoDeductCharges: true,
          autoDeductChargesCost: "1",
        },
        measureTemplate: {
          type: "",
          size: "",
          overrideColor: false,
          customColor: "",
          overrideTexture: false,
          customTexture: "",
        },
        attackName: "",
        actionType: "",
        attackBonus: "",
        critConfirmBonus: "",
        damage: {
          parts: [],
          critParts: [],
          nonCritParts: [],
        },
        attackParts: [],
        formulaicAttacks: {
          count: {
            formula: "",
          },
          bonus: {
            formula: "",
          },
          label: null,
        },
        formula: "",
        ability: {
          attack: null,
          damage: null,
          damageMult: 1,
          critRange: 20,
          critMult: 2,
        },
        save: {
          dc: 0,
          type: "",
          description: "",
        },
        effectNotes: [],
        attackNotes: [],
        soundEffect: "",
        changes: [
          {
            _id: "a9jyhbzr",
            formula: "12",
            operator: "add",
            subTarget: "spherebabAlchemy",
            modifier: "untyped",
            priority: 0,
            value: 12,
          },
        ],
        changeFlags: {
          loseDexToAC: false,
          noEncumbrance: false,
          mediumArmorFullSpeed: false,
          heavyArmorFullSpeed: false,
        },
        contextNotes: [],
        links: {
          children: [],
          charges: [],
        },
        tag: "",
        useCustomTag: false,
        armorProf: {
          value: [],
          custom: "",
        },
        weaponProf: {
          value: [],
          custom: "",
        },
        flags: {
          boolean: [],
          dictionary: [],
        },
        scriptCalls: [],
        featType: "classFeat",
        associations: {
          classes: [],
        },
        showInQuickbar: false,
        nonlethal: false,
        abilityType: "none",
        crOffset: "",
        disabled: false,
        conditionals: [],
        identifiedName: "Sphere BAB Feat",
      },
      effects: [],
      folder: null,
      sort: 0,
      permission: {
        default: 0,
        exBYpki8XOQ8AkUV: 3,
      },
      flags: {},
    },
  ],
  effects: [
    {
      _id: "eMXG7Qe0PBPOwdJd",
      changes: [],
      disabled: false,
      duration: {
        startTime: 0,
        startRound: 3,
        startTurn: 1,
      },
      icon: "modules/pf1spheres/assets/icons/battered.png",
      label: "",
      transfer: false,
      flags: {
        core: {
          statusId: "battered",
        },
      },
    },
  ],
  sort: 0,
  flags: {
    exportSource: {
      world: "087",
      system: "pf1",
      coreVersion: "0.8.8",
      systemVersion: "0.78.15",
    },
  },
} as FakeActorDataSource;
