_id: 8eBVPEHUhj2enWho
_key: '!items!8eBVPEHUhj2enWho'
effects: []
flags:
  pf1: {}
  pf1spheres:
    sphere: alchemy
folder: null
img: modules/pf1spheres/assets/icons/spheres/alchemy.webp
name: Lasting Application
sort: 0
system:
  ability:
    attack: null
    critMult: 2
    critRange: 20
    damage: null
    damageMult: 1
  abilityType: na
  actionType: null
  actions: []
  armorProf:
    custom: []
    value: []
  associations:
    classes: []
  attackBonus: ''
  attackName: ''
  attackNotes: []
  attackParts: []
  changeFlags:
    heavyArmorFullSpeed: false
    loseDexToAC: false
    mediumArmorFullSpeed: false
    noHeavyEncumbrance: false
    noMediumEncumbrance: false
  changes: []
  classSkills: {}
  contextNotes: []
  crOffset: ''
  critConfirmBonus: ''
  damage:
    critParts: []
    nonCritParts: []
    parts: []
  description:
    unidentified: ''
    value: >
      <p>Whenever you apply your poison to a weapon, the poison lasts for 1
      additional strike before it is consumed. For every 5 ranks in Craft
      (alchemy) you possess, it lasts for an additional strike.</p>
  disabled: false
  duration:
    units: ''
    value: null
  effectNotes: []
  flags:
    boolean: {}
    dictionary: {}
  formula: ''
  formulaicAttacks:
    bonus:
      formula: ''
    count:
      formula: ''
    label: null
  languages:
    custom: []
    value: []
  links:
    charges: []
    children: []
  nonlethal: false
  powerAttack:
    critMultiplier: 1
    damageBonus: 2
    multiplier: ''
  save:
    dc: 0
    description: ''
    type: ''
  scriptCalls: []
  showInQuickbar: false
  soundEffect: ''
  subType: combatTalent
  tag: ''
  tags: []
  target:
    value: ''
  uses:
    autoDeductChargesCost: '1'
    maxFormula: ''
    per: null
    rechargeFormula: ''
    value: 0
  weaponProf:
    custom: []
    value: []
type: feat

