_id: PVWumvovlwWAwTNJ
_key: "!items!PVWumvovlwWAwTNJ"
effects: []
flags:
  pf1: {}
folder: null
img: icons/svg/item-bag.svg
name: Environment Charge
sort: 0
system:
  ability:
    attack: null
    critMult: 2
    critRange: 20
    damage: null
    damageMult: 1
  abilityType: na
  acquired: false
  actions: []
  armorProf: []
  associations:
    classes: []
  attackBonus: ""
  attackName: ""
  attackNotes: []
  attackParts: []
  changeFlags:
    heavyArmorFullSpeed: false
    immuneToMorale: false
    loseDexToAC: false
    lowLightVision: false
    mediumArmorFullSpeed: false
    noHeavyEncumbrance: false
    noMediumEncumbrance: false
    seeInDarkness: false
    seeInvisibility: false
  changes: []
  classSkills: {}
  contextNotes: []
  crOffset: ""
  critConfirmBonus: ""
  damage:
    critParts: []
    nonCritParts: []
    parts: []
  description:
    instructions: ""
    unidentified: ""
    value: >
      <p>You maintain the power of a location even as you depart it.</p>

      <p><strong>Prerequisite:</strong> Charged Spells drawback.</p>

      <p><strong>Benefit:</strong> For the purpose of drawbacks or boons which
      alter your casting based on the location in which they are cast (such as
      the Area Bound or Terrain Casting drawbacks or the Atmoturgy or Draw Magic
      boons), you may determine all variables of any effect you create as if you
      were in the location in which you charged the effect rather than in the
      location in which you are casting the spell. This feat allows characters
      with the Terrain Casting drawback to cast spells in a blighted space so
      long as they prepared the spell charge in a non-blighted space.</p>
  disabled: false
  duration:
    units: ""
    value: null
  effectNotes: []
  flags:
    boolean: {}
    dictionary: {}
  formula: ""
  formulaicAttacks:
    bonus:
      formula: ""
    count:
      formula: ""
    label: null
  inherited: false
  languages: []
  links:
    charges: []
    children: []
  nonlethal: false
  racePoints: null
  save:
    dc: 0
    description: ""
    type: ""
  scriptCalls: []
  showInQuickbar: false
  simple: false
  soundEffect: ""
  subType: feat
  summons: false
  tag: ""
  tags:
    - Drawback
  target:
    value: ""
  traitCategory: ""
  traitType: ""
  uses:
    autoDeductChargesCost: "1"
    maxFormula: ""
    per: null
    rechargeFormula: ""
    value: 0
  weaponProf: []
type: feat
