#!/bin/sh

# SPDX-FileCopyrightText: 2022 Ethaks <ethaks@pm.me>
#
# SPDX-License-Identifier: EUPL-1.2

. "$(dirname "$0")/_/husky.sh"

if type reuse >/dev/null 2>&1; then
  reuse lint
fi
npx lint-staged
npm test
npm run typecheck
